version: '3.8'
services:
  mariadb:
    container_name: mariadb
    image: mariadb:10.11.5
    restart: always
    ports:
      - "3103:3306"
    environment: 
      MYSQL_ROOT_PASSWORD: "npm"
      MYSQL_DATABASE: "npm"
      MYSQL_USER: "npm"
      MYSQL_PASSWORD: "npm"
      MARIADB_AUTO_UPGRADE: "1"
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/log:/var/log/mysql
      - ./mysql/config:/etc/mysql/conf.d
      
    networks:
      - npm-net

networks:
  npm-net:
